### ISSUE TITLE
Zoneminder 

### ISSUE THREAD

**Issue by freedomlives** [nabbi/oubliette-overlay#1]
I am upgrading, having previously used mkr-overlay, which I see is less maintained than your overlay. 

zoneminder-9999 fails at "newins distros/ubuntu1204/zoneminder.logrotate zoneminder"
The solution is to change the directory to ubuntu2004

Next problem, when I run zmupdate.pl, I get "Can't locate Crypt/Eksblowfish/Bcrypt.pm in @INC" and again for the data entropy module. Therefore, I manually installed the following:
dev-perl/Crypt-Eksblowfish
dev-perl/Data-Entropy
Since the latter is in your overlay, I assume it was an oversight not to include it in dependencies. 

Otherwise, it all works great now!

**Comment by nabbi** [comment]
I'll incorporate those adjustments.
Yes I missed updating -9999, I had added those dependencies into 1.34.5

Are you able to validate -9999 again please ?

Thanks for the feedback.

**Comment by nabbi** [comment]
fix around 506d222c
