### ISSUE TITLE
www-misc/zoneminder needs another dependency in latest version

### ISSUE THREAD

**Issue by freedomlives** [nabbi/oubliette-overlay#10]
Hi,

Very happy that you're keeping up this package! 

Noticed that my filters aren't working, got error as shown in the image suggesting MIME::Entity perl modules is needed.
![Screenshot_zoneminder](https://user-images.githubusercontent.com/16663872/205387394-82007168-3f46-420d-bd3e-d4741b6894b7.png)

Installing dev-perl/MIME-tools fixed this problem.

**Comment by nabbi** [comment]
Ah. Good catch. I use the new mail modules so hadn't encountered this dependency issue.
