### ISSUE TITLE
www-misc/zoneminder - gentoo ebuild fail on dependency download.

### ISSUE THREAD

**Issue by lyallp** [nabbi/oubliette-overlay#12]
fails to fetch FriendsOfCake/crud.git 
Is there any way of making this ebuild less sensitive to this sort of problem?
Otherwise, I thank you for your efforts so far :)

 * Fetching https://github.com/FriendsOfCake/crud.git ...
git fetch https://github.com/FriendsOfCake/crud.git --prune +refs/heads/*:refs/heads/* +refs/tags/*:refs/tags/* +refs/notes/*:refs/notes/* +refs/pull/*/head:refs/pull/* +HEAD:refs/git-r3/HEAD
git update-ref --no-deref refs/git-r3/www-misc/zoneminder/0/web_api_app_Plugin_Crud/__main__0bd63fb464957080ead342db58ca9e01532cf1ef
fatal: update_ref failed for ref 'refs/git-r3/www-misc/zoneminder/0/web_api_app_Plugin_Crud/__main__': cannot update ref 'refs/git-r3/www-misc/zoneminder/0/web_api_app_Plugin_Crud/__main__': trying to write ref 'refs/git-r3/www-misc/zoneminder/0/web_api_app_Plugin_Crud/__main__' with nonexistent object 0bd63fb464957080ead342db58ca9e01532cf1ef
 * ERROR: www-misc/zoneminder-9999::oubliette failed (unpack phase):
 *   Referencing 0bd63fb464957080ead342db58ca9e01532cf1ef failed (wrong ref?).

**Comment by nabbi** [comment]
confirmed master and release-1.36 trunks have the sub modules correct as of today (Again)
