### ISSUE TITLE
zoneminder manifest generation issue?

### ISSUE THREAD

**Issue by zmuser** [nabbi/oubliette-overlay#2]
hi!
this is the message i got:

Verifying ebuild manifests
!!! Digest verification failed:
!!! /var/lib/layman/oubliette/www-misc/zoneminder/files/README.gentoo
!!! Reason: Filesize does not match recorded size
!!! Got: 1347
!!! Expected: 1140

Thanks!

**Comment by nabbi** [comment]
Whoops. Sorry about that. I copied readme from mk-overlay and forget to fix the digests
