### ISSUE TITLE
www-misc/zoneminder don't force apache2 & cgi php sapi

### ISSUE THREAD

**Issue by dekeonus** [nabbi/oubliette-overlay#5]
https://github.com/nabbi/oubliette-overlay/blob/8f4177b4abd7b36100b17697455893fee750f53d/www-misc/zoneminder/zoneminder-1.36.21.ebuild#L36-L38

Zoneminder does not NEED the apache2 sapi, the ebuild should not force it. It should especially not force cgi AND apache2 sapi
The depend on virtual/httpd-php ensures we get one of cgi, apache2 and/or fpm (that is after all what that virtual package is supposed to do)
https://github.com/nabbi/oubliette-overlay/blob/8f4177b4abd7b36100b17697455893fee750f53d/www-misc/zoneminder/zoneminder-1.36.21.ebuild#L67

**Comment by nabbi** [comment]
167a421 has this incorporated in 1.36.33-r1, 1.36.9999, and 1.36.9999-r1
Thanks again!
