### ISSUE TITLE
www-misc/zoneminder -DHAVE_LIBGNUTLS and -DHAVE_LIBGCRYPT have no effect for cmake's configure

### ISSUE THREAD

**Issue by dekeonus** [nabbi/oubliette-overlay#8]
cmake resets these cache values when it runs (From CMakeLists.txt): 
```
# gcrypt (using find_library and find_path)
find_library(GCRYPT_LIBRARIES gcrypt)
if(GCRYPT_LIBRARIES)
  set(HAVE_LIBGCRYPT 1)
```
These libraries can be still be disabled by cheating: if the searched library variable (GCRYPT_LIBRARIES above) is already set cmake won't reset it. So something akin to

```
    perl_set_version
    export TZ=UTC # bug 630470

    local myconf
    if ! use gcrypt; then
        myconf+=" -DGCRYPT_LIBRARIES=0"
    fi
    if ! use gnutls; then
        myconf+=" -DGNUTLS_LIBRARIES=0"
    fi

    mycmakeargs=(
        -DZM_TMPDIR=/var/tmp/zm
##=== trimmed ===
        -DCMAKE_DISABLE_FIND_PACKAGE_OpenSSL="$(usex ssl OFF ON)"
        ${myconf}
    )
```
However this isn't needed for the live build (for one the gcrypt support was dropped):
```
        -DZM_JWT_BACKEND="$(usex gnutls libjwt jwt-cpp)"
        -DZM_CRYPTO_BACKEND="$(usex gnutls gnutls openssl)"

```
It is also worth noting that gnutls can not be used unless you are using libjwt (this has been the case since somepoint in the 1.34.xx release cycle)
dev-libs/libjwt is not packaged in gentoo - I do have an ebuild. but it also requires patching zoneminder's cmake module to find libjwt: It is expecting the library to have been named libjwt-gnutls - other distributions building the library twice once with openssl and once with gnutls (the ebuild I have just builds it once with a USE flag to choose the linking).

EDIT: Now the dev-libs/libjwt ebuild I have builds both gnutls and openssl libraries, so zoneminder no longer needs it's cmake modules to be pached

**Comment by nabbi** [comment]
167a421 has this incorporated in 1.36.33-r1, 1.36.9999, and 1.36.9999-r1

LMK if the changes for this aren't reflected appropriately 

Thanks again!
