### ISSUE TITLE
www-misc/zoneminder missing mysql server depend and missing optional perl module depends

### ISSUE THREAD

**Issue by dekeonus** [nabbi/oubliette-overlay#9]
With `virtual/mysql` removed from the DEPEND stanzas there is now no package in the depgraph that pulls in a mysql compatible server. This isn't necessarily a bad thing, however a new user can't do anything with the package until they install one or have access to one over the network. I suggest using the `optfeature` eclass to let the user know.

There are a few optional perl modules that ZoneMinder uses for some odds and ends, it would be nice if users were told about them.

\#\# used to get verbose responses from onvif cameras
XML::LibXML  =>  dev-perl/XML-LibXML

\#\# used to authenticate for onvif event monitoring
 _# all three are from same package_
SOAP::Lite
SOAP::Server::Parameters
SOAP::Transport::HTTP  =>  dev-perl/SOAP-Lite

\#\# used during event creation to set image dimensions
Image::Info  =>  dev-perl/Image-Info

\#\# The older way to email a notice to a user
MIME::Entity  =>  dev-perl/MIME-tools
 _\# if the ZM_NEW_MAIL_MODULES is set true then_
 _\# MIME::Lite && Net::SMTP are used (which are already in depgraph)_

\#\# for archiving an event to a sftp server
Net::SFTP::Foreign  =>  dev-perl/Net-SFTP-Foreign

\#\# for copying an event to An Amazon S3 bucket
Net::Amazon::S3  =>  dev-perl/Net-Amazon-S3
File::Slurp  =>  dev-perl/File-Slurp

add `inherit optfeature` to the header of the ebuild
and in the pkg_postinst something akin to the following (though I still think that the onvif stuff should be under a USE flag esp. with the live ebuild as that would cover net-libs/gsoap as well)
I'd personally put this above the legacy config file section
```
pkg_postinst() {
elog "This package requires access to a Mysql compatible database server"
elog "ZoneMinder can connect to a remote database if desired"
optfeature_header "Mysql compatible database server"
optfeature "Install if you don't already have one" virtual/mysql
elog " "
elog "there are some optional features/enhancements that can be added"
optfeature_header "Onvif Access"
optfeature "Verbose responses from camera" dev-perl/XML-LibXML
optfeature "Event monitoring" dev-perl/SOAP-Lite
optfeature_header "Email"
optfeature "Older email package (if new one isn't working)" dev-perl/MIME-tools
optfeature_header "Event creation enhancements"
optfeature "Retrieves image size" dev-perl/Image-Info
optfeature_header "Storage"
optfeature "Archive to SFTP server" dev-perl/Net-SFTP-Foreign
optfeature "Copy to Amazon S3 bucket" dev-perl/Net-Amazon-S3 dev-perl/File-Slurp
}
```

**Comment by nabbi** [comment]
167a421 has this incorporated in 1.36.33-r1, 1.36.9999, and 1.36.9999-r1
Thanks again!
